[build]
publish = "dist"
command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm run build"

[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--version"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
